version: '2'

services:
    db:
        image: postgres
    redis:
        image: redis
    web:
        build: .
        command: ./docker-entrypoint-web.sh
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - "db"
            - "redis"
