# Generated by Django 2.0 on 2017-12-23 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0002_question_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 20, 34, 15, 40988, tzinfo=utc)),
        ),
    ]
